// <auto-generated />
using System;
using Game.Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Backend.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Game.Backend.Database.AccountEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PasswordIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.AccountSessionEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AccountSessions", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.CloudSaveEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClientSavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("TEXT");

                    b.Property<int>("SaveVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("CloudSaves", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.EntitlementEntity", b =>
                {
                    b.Property<Guid>("EntitlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourcePurchaseReceiptId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntitlementId");

                    b.HasIndex("SourcePurchaseReceiptId");

                    b.HasIndex("AccountId", "ProductId")
                        .IsUnique();

                    b.ToTable("Entitlements", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.GameConfigVersionEntity", b =>
                {
                    b.Property<string>("ConfigVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigVersion");

                    b.HasIndex("IsActive");

                    b.ToTable("GameConfigVersions", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.IdempotencyKeyEntity", b =>
                {
                    b.Property<Guid>("IdempotencyKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("TEXT");

                    b.HasKey("IdempotencyKeyId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("AccountId", "Action", "RequestId")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.PlayerEntity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bandwidth")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CoreFragments")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Data")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Efficiency")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Energy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hardening")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Integrity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastResourceClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Matter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Output")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Processing")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantumCores")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("AccountId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.PlayerUpgradeEntity", b =>
                {
                    b.Property<Guid>("PlayerUpgradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpgradeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerUpgradeId");

                    b.HasIndex("PlayerId", "UpgradeId")
                        .IsUnique();

                    b.ToTable("PlayerUpgrades", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.PurchaseReceiptEntity", b =>
                {
                    b.Property<Guid>("PurchaseReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseReceiptId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReceiptHash")
                        .IsUnique();

                    b.ToTable("PurchaseReceipts", (string)null);
                });

            modelBuilder.Entity("Game.Backend.Database.AccountSessionEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Game.Backend.Database.CloudSaveEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.PlayerEntity", "Player")
                        .WithOne()
                        .HasForeignKey("Game.Backend.Database.CloudSaveEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Database.EntitlementEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Backend.Database.PurchaseReceiptEntity", "SourcePurchaseReceipt")
                        .WithMany()
                        .HasForeignKey("SourcePurchaseReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("SourcePurchaseReceipt");
                });

            modelBuilder.Entity("Game.Backend.Database.IdempotencyKeyEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Backend.Database.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Database.PlayerEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Game.Backend.Database.PlayerUpgradeEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Game.Backend.Database.PurchaseReceiptEntity", b =>
                {
                    b.HasOne("Game.Backend.Database.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game.Backend.Database.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
